# Generated by Django 3.0.3 on 2020-06-03 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_auto_20200603_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logs.Comment', verbose_name='Объявление'),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
