# Generated by Django 3.0.3 on 2020-06-17 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_auto_20200603_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
    ]
