# Generated by Django 3.0.3 on 2020-06-24 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0005_remove_comment_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['date_added'], 'verbose_name': 'ОТЗЫВЫ', 'verbose_name_plural': 'Меню вкладки: ОТЗЫВЫ'},
        ),
    ]
