# Generated by Django 3.0.3 on 2020-06-24 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20200419_1639'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'УСЛУГИ', 'verbose_name_plural': 'Меню вкладки: УСЛУГИ'},
        ),
    ]
