# Generated by Django 3.0.3 on 2020-07-12 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='image_1',
            field=models.ImageField(default=1, upload_to='images', verbose_name='ИЗОБРАЖЕНИЕ_1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photos',
            name='image_2',
            field=models.ImageField(default=1, upload_to='images', verbose_name='ИЗОБРАЖЕНИЕ_2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photos',
            name='image_3',
            field=models.ImageField(default=1, upload_to='images', verbose_name='ИЗОБРАЖЕНИЕ_3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photos',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='ИЗОБРАЖЕНИЕ_4'),
        ),
        migrations.AddField(
            model_name='photos',
            name='image_5',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='ИЗОБРАЖЕНИЕ_5'),
        ),
        migrations.AddField(
            model_name='photos',
            name='image_6',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='ИЗОБРАЖЕНИЕ_6'),
        ),
        migrations.AddField(
            model_name='photos',
            name='image_7',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='ИЗОБРАЖЕНИЕ_7'),
        ),
        migrations.AddField(
            model_name='photos',
            name='image_8',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='ИЗОБРАЖЕНИЕ_8'),
        ),
        migrations.AddField(
            model_name='photos',
            name='image_9',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='ИЗОБРАЖЕНИЕ_9'),
        ),
        migrations.AddField(
            model_name='photos',
            name='index',
            field=models.IntegerField(default=1, verbose_name='Номер'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photos',
            name='top',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='image.Photos', verbose_name='Вывод названия объекта'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Наименования объекта'),
        ),
    ]
