# Generated by Django 3.0.3 on 2020-04-28 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0006_auto_20200428_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newswork',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='image.NewsWork'),
        ),
    ]
