# Generated by Django 3.0.3 on 2020-04-28 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0012_auto_20200428_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newswork',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='image.NewsWork'),
        ),
    ]
