# Generated by Django 3.0.3 on 2020-04-28 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0013_auto_20200428_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newswork',
            name='title',
            field=models.CharField(blank=True, max_length=600),
        ),
    ]
