# Generated by Django 3.0.3 on 2020-04-28 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0014_auto_20200428_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newswork',
            name='status',
            field=models.CharField(blank=True, choices=[(models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='image.NewsWork'), models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='image.NewsWork')), ('o', 'On loan'), ('a', 'Available'), ('r', 'Reserved')], default=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='image.NewsWork'), max_length=1),
        ),
    ]
