# Generated by Django 3.0.3 on 2020-04-28 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0015_auto_20200428_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newswork',
            name='status',
            field=models.CharField(blank=True, choices=[('m', 'main'), ('o', 'On loan'), ('a', 'Available'), ('r', 'Reserved')], default='m', max_length=1),
        ),
    ]
