# Generated by Django 3.0.3 on 2020-04-07 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20200407_1757'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Редактирование услуги', 'verbose_name_plural': 'Редактирование услуги'},
        ),
    ]
