# Generated by Django 3.0.3 on 2020-04-10 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_entry_topic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entry',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
