# Generated by Django 3.0.3 on 2020-04-12 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_auto_20200411_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
