# Generated by Django 3.0.3 on 2020-04-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_auto_20200412_0610'),
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.ImageField(upload_to='uploads/% Y/% m/% d/')),
            ],
            options={
                'verbose_name': 'Наименование',
                'verbose_name_plural': 'Вкладка"Наши работы"',
            },
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Наименование услуги', 'verbose_name_plural': 'Вкладка "Услуги"'},
        ),
    ]
