# Generated by Django 3.0.3 on 2020-04-13 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0012_auto_20200413_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок описания')),
                ('description', models.TextField(verbose_name='Комментарий')),
                ('photo', models.ImageField(upload_to='user_flowers', verbose_name='Загрузка')),
            ],
        ),
        migrations.DeleteModel(
            name='SimpleAddFlower',
        ),
    ]
