# Generated by Django 3.0.3 on 2020-04-14 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0013_auto_20200413_2036'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Img',
            new_name='News_Work',
        ),
        migrations.AlterModelOptions(
            name='news_work',
            options={'verbose_name_plural': 'Вкладка  __Наши работы__'},
        ),
    ]
