# Generated by Django 3.0.3 on 2020-04-14 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0014_auto_20200414_0845'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news_work',
            options={'verbose_name': 'Вкладка  __Наши работы__', 'verbose_name_plural': 'Вкладка  __Наши работы__'},
        ),
    ]
