# Generated by Django 3.0.3 on 2020-04-14 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0015_auto_20200414_0939'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News_Work',
            new_name='Img',
        ),
    ]
