# Generated by Django 3.0.3 on 2020-04-15 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0016_auto_20200414_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='photo',
            field=models.ImageField(default='user_flowers/None/no-img.jpg', upload_to='user_flowers', verbose_name='Загрузка'),
        ),
    ]
