# Generated by Django 3.0.3 on 2020-04-15 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0018_img_dated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='dated',
            field=models.DateField(auto_now_add=True),
        ),
    ]
