# Generated by Django 3.0.3 on 2020-04-18 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0020_auto_20200415_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='img',
            name='description',
        ),
        migrations.RemoveField(
            model_name='img',
            name='title',
        ),
        migrations.AlterField(
            model_name='img',
            name='dated',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата'),
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Наименование')),
                ('description', models.TextField(verbose_name='Комментарий')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mysite.Img')),
            ],
            options={
                'verbose_name': 'Вкладка  __Наши работы__',
                'verbose_name_plural': 'Вкладка  __Наши работы__Комментарий ',
            },
        ),
    ]
