# Generated by Django 3.0.3 on 2020-04-18 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0021_auto_20200418_0914'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Наименование')),
                ('description', models.TextField(verbose_name='Комментарий')),
                ('photo', models.ImageField(default='user_flowers/None/no-img.jpg', upload_to='user_flowers', verbose_name='Загрузка')),
                ('dated', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Вкладка  __Наши работы__',
                'verbose_name_plural': 'Вкладка  __Наши работы__',
            },
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
        migrations.DeleteModel(
            name='Img',
        ),
    ]
