# Generated by Django 3.0.3 on 2020-04-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0022_auto_20200418_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('profile_text', models.TextField()),
                ('profile_title', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='Imag',
        ),
    ]
