# Generated by Django 3.0.3 on 2020-04-18 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0024_auto_20200418_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='user',
        ),
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
