# Generated by Django 3.0.3 on 2020-04-19 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0025_auto_20200418_1623'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
