# Generated by Django 3.0.3 on 2020-04-19 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0026_delete_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
