# Generated by Django 3.0.3 on 2020-07-12 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0028_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'КОНТАКТЫ', 'verbose_name_plural': 'Меню вкладки: КОНТАКТЫ'},
        ),
        migrations.AddField(
            model_name='contact',
            name='city',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Город'),
        ),
    ]
