# Generated by Django 3.0.3 on 2020-08-05 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0029_auto_20200712_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='city',
        ),
    ]
